- hosts: localhost
  gather_facts: false
  connection: local

- name: "[AWS] create vpc"
  import_playbook: aws_create_vpc.yaml

- name: "[AWS] create windows vm"
  import_playbook: aws_create_windows_ec2_instance.yaml

- name: "[AWS] create linux vm"
  import_playbook: aws_create_linux_ec2_instance.yaml
