---
- hosts: all

  vars_prompt:
    - name: user
      prompt: "Enter windows user"
    - name: password
      prompt: "Enter password for windows user"

  vars:
    ansible_user: "{{ user }}"
    ansible_password: "{{ password }}"
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore

  tasks:
    - name: Run Ping
      win_ping:
